/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */
Serial port = new Serial(this,Serial.list()[2],9600);
public void stick1_change1(GStick source, GEvent event) { //_CODE_:stick1:732060:
  println("stick1 - GStick >> GEvent." + event + " @ " + stick1.getPosition());
  port.write(stick1.getPosition());
} //_CODE_:stick1:732060:

public void stick2_change1(GStick source, GEvent event) { //_CODE_:stick2:728182:
  println("stick2 - GStick >> GEvent." + event + " @ " + stick2.getStickY());
  port.write(stick2.getStickY()+10);
} //_CODE_:stick2:728182:

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:738673:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
  port.write(7);
} //_CODE_:button1:738673:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  stick1 = new GStick(this, 307, 140, 60, 60);
  stick1.setMode(G4P.X4);
  stick1.setOpaque(false);
  stick1.addEventHandler(this, "stick1_change1");
  stick2 = new GStick(this, 107, 136, 60, 60);
  stick2.setMode(G4P.X4);
  stick2.setOpaque(false);
  stick2.addEventHandler(this, "stick2_change1");
  button1 = new GButton(this, 197, 150, 80, 30);
  button1.setText("Face text");
  button1.addEventHandler(this, "button1_click1");
}

// Variable declarations 
// autogenerated do not edit
GStick stick1; 
GStick stick2; 
GButton button1; 